[package]
name = "mec-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mec_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
numpy = "0.27"
